oahu_cities = [
    "Honolulu", "Waikiki", "Ala Moana", "Kakaako", "Manoa", "Kalihi", "Palolo",
    "Makiki", "Moanalua", "Kaimuki", "Kapahulu", "Kahala", "Waialae", "Diamond Head",
    "Aina Haina", "Hawaii Kai", "Portlock", "Waimanalo", "Kailua", "Lanikai", "Kaneohe",
    "Kaneohe Bay", "Heeia", "Kahalu'u", "Laie", "Hauula", "Punaluu", "Kaawa", "Kahuku",
    "Sunset Beach", "Pupukea", "Haleiwa", "Waimea Bay", "Waialua", "Mokuleia",
    "Schofield Barracks", "Wahiawa", "Mililani", "Mililani Mauka", "Waipio", "Waikele",
    "Waipahu", "Pearl City", "Aiea", "Halawa", "Moanalua", "Salt Lake", "Hickam Housing",
    "Pearl Harbor", "Ford Island", "Ewa Beach", "Ewa Gentry", "Kapolei", "Ko Olina",
    "Makakilo", "Nanakuli", "Maili", "Waianae", "Makaha", "Makaha Valley"
]

civil_engineering_terms = [
    "bearing capacity", "boring holes", "soil compaction", "concrete mix", 
    "compressive strength", "tensile strength", "shear force", "bending moment", 
    "retaining wall", "footing", "foundation", "slab", "grade beam", 
    "pile foundation", "geotechnical investigation", "soil stabilization", 
    "earthwork", "grading", "cut and fill", "embankment", "settlement", 
    "slope stability", "drainage", "stormwater management", "erosion control", 
    "silt fence", "retention basin", "detention basin", "culvert", 
    "catch basin", "manhole", "sewer system", "sanitary sewer", 
    "septic tank", "water table", "aquifer", "groundwater", "permeability", 
    "porosity", "capillary action", "consolidation", "expansive soil", 
    "frost heave", "pavement design", "flexible pavement", "rigid pavement", 
    "asphalt", "bitumen", "concrete", "reinforcement", "rebar", 
    "prestressed concrete", "post-tensioning", "anchor bolts", "structural analysis", 
    "truss", "girder", "beam", "column", "lintel", "joist", "riser", 
    "tread", "formwork", "scaffolding", "shoring", "bracing", "cantilever", 
    "load-bearing wall", "partition wall", "masonry", "brickwork", 
    "blockwork", "cladding", "facade", "curtain wall", "roof truss", 
    "roof pitch", "gable", "hip roof", "valley", "eaves", "fascia", 
    "soffit", "rafter", "purlin", "roof deck", "roof insulation", 
    "waterproofing", "vapor barrier", "roof drainage", "gutter", 
    "downspout", "flashing", "parapet", "thermal expansion", 
    "contraction joint", "expansion joint", "control joint", "dowel bar", 
    "concrete curing", "hydration", "shrinkage", "cracking", "spalling", 
    "reinforcement detailing", "lap splice", "development length", 
    "anchorage", "tie beam", "ring beam", "plinth", "kerb", "curb", 
    "paving", "paver block", "granular subbase", "aggregate", 
    "crushed stone", "gravel", "sand", "fine aggregate", "coarse aggregate", 
    "cement", "hydrated lime", "gypsum", "pozzolan", "admixture", 
    "plasticizer", "superplasticizer", "retarder", "accelerator", 
    "air-entraining agent", "water-cement ratio", "slump test", 
    "compaction test", "proctor test", "nuclear density test", 
    "moisture content", "Atterberg limits", "liquid limit", "plastic limit", 
    "plasticity index", "shear strength", "direct shear test", 
    "triaxial shear test", "unconfined compression test", "plate load test", 
    "standard penetration test", "cone penetration test", "dynamic cone penetrometer", 
    "borehole", "test pit", "trial trench", "soil classification", 
    "Unified Soil Classification System", "AASHTO soil classification", 
    "rock classification", "RMR", "Q-system", "rock mass rating", 
    "excavation", "blasting", "rock bolting", "shotcrete", "rock anchor", 
    "tieback", "grouting", "jet grouting", "slurry wall", "diaphragm wall", 
    "secant pile wall", "contiguous pile wall", "sheet piling", "cofferdam", 
    "caisson", "well foundation", "pile driving", "pile load test", 
    "pile cap", "pile group", "raft foundation", "mat foundation", 
    "spread footing", "combined footing", "strip footing", "eccentric footing", 
    "balanced cantilever", "precast concrete", "precast beam", "precast column", 
    "precast slab", "precast panel", "precast wall", "tilt-up construction", 
    "modular construction", "prefabricated building", "site grading", 
    "site plan", "topographic survey", "contour map", "geodetic survey", 
    "leveling", "total station", "GPS survey", "hydrographic survey", 
    "as-built survey", "property boundary survey", "right-of-way", 
    "easement", "land acquisition", "land development", "zoning", 
    "building code", "construction permit", "environmental impact assessment", 
    "sustainable design", "green building", "LEED certification", 
    "energy efficiency", "carbon footprint", "renewable energy", 
    "solar energy", "wind energy", "geothermal energy", "hydroelectric power", 
    "rainwater harvesting", "greywater recycling", "wastewater treatment", 
    "solid waste management", "landfill", "recycling plant", "incineration", 
    "composting", "hazardous waste", "asbestos", "lead paint", 
    "toxic waste", "contaminated soil", "brownfield site", "remediation", 
    "groundwater remediation", "bioremediation", "phytoremediation", 
    "soil vapor extraction", "air sparging", "chemical oxidation", 
    "thermal desorption", "capping", "containment", "environmental monitoring", 
    "air quality monitoring", "water quality monitoring", "noise monitoring", 
    "vibration monitoring", "construction management", "project management", 
    "project scheduling", "critical path method", "PERT", "Gantt chart", 
    "construction contract", "bidding", "tendering", "contract administration", 
    "change order", "construction claim", "dispute resolution", 
    "arbitration", "mediation", "construction safety", "personal protective equipment", 
    "fall protection", "scaffold safety", "confined space entry", 
    "lockout/tagout", "electrical safety", "fire safety", "hazardous materials", 
    "ergonomics", "construction quality control", "quality assurance", 
    "materials testing", "concrete testing", "steel testing", "welding inspection", 
    "non-destructive testing", "ultrasonic testing", "radiographic testing", 
    "magnetic particle testing", "dye penetrant testing", "visual inspection", 
    "structural health monitoring", "bridge inspection", "building inspection", 
    "infrastructure assessment", "asset management", "facility management", 
    "maintenance management", "life cycle analysis", "cost estimation", 
    "quantity surveying", "value engineering", "risk management", 
    "insurance", "bonding", "construction finance", "progress payment", 
    "retention", "cash flow", "construction accounting", "construction law", 
    "building information modeling", "BIM", "computer-aided design", 
    "CAD", "geographic information system", "GIS", "remote sensing", 
    "aerial photography", "drone survey", "3D scanning", "laser scanning", 
    "virtual reality", "augmented reality", "construction technology", 
    "prefabrication", "automation", "robotics", "3D printing", 
    "smart materials", "nanotechnology", "sensors", "IoT in construction", 
    "construction software", "project management software", "building energy modeling", 
    "energy simulation", "daylighting analysis", "thermal modeling", 
    "CFD analysis", "wind analysis", "seismic analysis", "earthquake engineering", 
    "retrofit", "structural retrofitting", "seismic retrofit", 
    "base isolation", "dampers", "earthquake-resistant design", 
    "tsunami design", "flood control", "coastal engineering", 
    "harbor engineering", "marine structures", "offshore structures", 
    "underwater construction", "tunneling", "mining engineering", 
    "subsurface engineering", "geotechnical engineering", "structural engineering", 
    "environmental engineering", "transportation engineering", 
    "traffic engineering", "highway engineering", "railway engineering", 
    "airport engineering", "bridge engineering", "tunnel engineering", 
    "hydraulic engineering", "water resources engineering", "hydrology", 
    "hydraulic design", "dam design", "reservoir design", "canal design", 
    "irrigation design", "floodplain management", "urban drainage", 
    "stormwater design", "wastewater design", "water supply design", 
    "pipeline design", "pump station design", "water treatment plant design", 
    "wastewater treatment plant design", "solid waste management facility design", 
    "landfill design",
 "hazardous waste management", "air pollution control", 
    "noise control", "environmental remediation design", "environmental impact analysis", 
    "sustainable infrastructure design", "resilient infrastructure", 
    "disaster risk reduction", "climate change adaptation", "coastal protection", 
    "shoreline stabilization", "wetland restoration", "habitat restoration", 
    "ecosystem services", "biodiversity", "environmental conservation", 
    "environmental policy", "regulatory compliance", "environmental standards", 
    "ISO 14001", "sustainability standards", "carbon management", 
    "carbon sequestration", "carbon trading", "emissions trading", 
    "carbon offset", "renewable energy design", "green infrastructure", 
    "low-impact development", "green roofs", "permeable pavements", 
    "urban heat island effect", "cool roofs", "cool pavements", 
    "energy-efficient building design", "net-zero energy building", 
    "passive solar design", "natural ventilation", "daylighting", 
    "green building materials", "recycled materials", "bio-based materials", 
    "certified wood", "sustainable construction practices", "construction waste management", 
    "deconstruction", "material reuse", "construction logistics", 
    "construction supply chain", "just-in-time delivery", "construction equipment", 
    "heavy machinery", "cranes", "excavators", "bulldozers", "graders", 
    "loaders", "backhoes", "dump trucks", "concrete mixers", "concrete pumps", 
    "asphalt pavers", "rollers", "compactors", "pile drivers", 
    "tunnel boring machines", "drilling rigs", "construction scaffolding", 
    "construction formwork", "construction shoring", "construction bracing", 
    "construction hoists", "construction elevators", "construction site safety", 
    "construction site management", "construction traffic management", 
    "site security", "site access control", "site surveillance", 
    "construction signage", "site layout planning", "temporary works", 
    "construction sequence planning", "construction work packages", 
    "work breakdown structure", "project baseline", "project tracking", 
    "earned value management", "construction productivity", "construction efficiency", 
    "lean construction", "construction best practices", "construction innovation", 
    "construction process improvement", "continuous improvement", 
    "lessons learned", "knowledge management", "construction documentation", 
    "as-built documentation", "construction records", "construction photography", 
    "construction progress reporting", "construction daily reports", 
    "construction diaries", "construction logs", "construction drawings", 
    "shop drawings", "fabrication drawings", "erection drawings", 
    "construction submittals", "product data", "material samples", 
    "mock-ups", "construction inspections", "site inspections", 
    "third-party inspections", "special inspections", "construction testing", 
    "field testing", "laboratory testing", "construction monitoring", 
    "quality control plan", "quality assurance plan", "construction", "bearing pressure", "bearing strata", "bedrock", "blow count", 
    "borehole logging", "capillary fringe", "clay fraction", "cohesionless soil", 
    "consolidation settlement", "critical state soil mechanics", "effective stress", 
    "geogrid", "geomembrane", "geonet", "geosynthetic clay liner", 
    "geotextile", "geotechnical centrifuge", "gravel pack", "ground improvement", 
    "grouting", "hydraulic conductivity", "k0 condition", "liquefaction", 
    "lithostatic pressure", "long-term settlement", "overburden pressure", 
    "peat", "permafrost", "plate load test", "plaxis", 
    "pore water pressure", "pressuremeter test", "pseudo-static analysis", 
    "residual soil", "rotary drilling", "sand fraction", "secant modulus", 
    "seepage", "settlement monitoring", "shear box test", "shear modulus", 
    "shear wave velocity", "shrink-swell index", "soil column analysis", 
    "soil creep", "soil investigation", "soil nailing", "soil profiling", 
    "soil-structure interaction", "specific gravity of soil", "stress path method", 
    "subgrade reaction modulus", "surface settlement", "surcharge load", 
    "swelling pressure", "triaxial test", "unconsolidated soil", 
    "undrained shear strength", "unit weight of soil", "vane shear test", 
    "void ratio", "wall friction", "yield stress", "zone of influence"]